version: "3"

volumes:
  db-data: {}
#  zk-data: {}
#  zk-txn: {}
#  zk-conf: {}
#  kafka-data: {}
#  kafka-logs: {}

services:
  wms_db:
    container_name: wms_database
    image: postgres:latest
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}

  zookeeper:
    container_name: wms_zookeeper
    image: confluentinc/cp-zookeeper:5.3.0
    restart: always
    ports:
      - "63000:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
  #    volumes:
  #      - zk-data:/var/lib/zookeeper/data # for Data
  #      - zk-txn-logs:/var/lib/zookeeper/log # for transaction logs
  #      - zk-conf:/etc/zookeeper # for configuration files

  kafka:
    container_name: wms_kafka
    image: confluentinc/cp-kafka:5.3.0
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  #    volumes:
  #      - kafka-data:/var/lib/kafka/data
  #      - kafka-logs:/var/lib/kafka/logs
#  kafka-ui:
#    image: provectuslabs/kafka-ui
#    container_name: kafka-ui
#    ports:
#      - "8082:8080"
#    restart: always
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=local
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
#      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
#      - KAFKA_CLUSTERS_0_READONLY=true
#    depends_on:
#      - kafka
#      - zookeeper
